@ApiToken = 

## Add policy
POST http://localhost:7071/api/AddPolicy
Content-Type: application/json
Authorization: {{ApiToken}}

{
	"category": "Finance",
	"displayName": "Test Policy 01",
	"description": "This is a test policy rule",
	"rule": "if (userName == \"juswen@microsoft.com\") { return \"allow\"; } else { return \"deny\"; }"
}
###
@policyId = f5f22984-d3b1-402a-bbe3-23e686f95a50

## Fetch policies
GET http://localhost:7071/api/FetchPolicies?category=Finance
Authorization: {{ApiToken}}
###

## Update user policy
POST http://localhost:7071/api/AddUserPolicy
Content-Type: application/json
Authorization: {{ApiToken}}

{
	"policyId": "{{policyId}}",
	"policyCategory": "Finance"
}
###

## Validate
GET http://localhost:7071/api/Validate?context=/user/profile
Authorization: {{ApiToken}}
###